baseURL = "https://bothell.urbanism-guide.com/"
title = "Bothell Urbanism Guide"

[module]
[[module.imports]]
path = "github.com/prestomation/urbanism-guide-core"

[params]
  description = "A practical guide for Bothell urbanists and advocates. Understand the issues, learn the terms, and show up ready to contribute."
  goatCounterCode = "bothell-urbanism-guide"
  BookRepo = "https://github.com/prestomation/bothell-urbanism-guide"
  BookEditPath = "edit/main/content"
