name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    uses: prestomation/urbanism-guide-core/.github/workflows/deploy.yml@v0.1.0
    with:
      timezone: "America/Los_Angeles"
    permissions:
      contents: write
