name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    permissions:
      contents: write
      pull-requests: write
    uses: prestomation/urbanism-guide-core/.github/workflows/pr-preview.yml@v0.3.0
    with:
      timezone: "America/Los_Angeles"
      base_url: "https://bothell.urbanism-guide.com"
